name: GitHub Actions CodePipeline
run-name: ${{ github.actor }} action for codepipeline 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Webhook
        uses: distributhor/workflow-webhook
        with:
          url: "https://0u70r6cxkd.execute-api.eu-west-1.amazonaws.com/prod/webhook"
          #json: '{ "repository": "${{github.event.repository.full_name}}", "number": "${{github.event.number}}", "created_at": "${{github.event.pull_request.created_at}}", "updated_at": "${{github.event.pull_request.updated_at}}" }'
          json: '{ "repository": "${{github.event.repository.full_name}}", "ref": "${{github.event.branch}}", "ref_type": "branch", "description": "multi pipeline wunger" }'